Layout/ExtraSpacing:
  Exclude:
    - 'config/puma.rb'

Layout/SpaceAfterComma:
  Exclude:
    - 'config/puma.rb'

Layout/SpaceBeforeFirstArg:
  Exclude:
    - 'config/puma.rb'

Lint/NestedMethodDefinition:
  Exclude:
    - 'app/controllers/random_request_reviews_controller.rb'

Metrics/AbcSize:
  Max: 30
  
Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: false
