version: "2"

services:

  #
  # メインコンテナ
  #
  web:
    build:
      context: .

    volumes:
      - .:/app
    ports:
      - "3500:3500"

    environment:
      RAILS_ENV: development

    command: puma -C config/puma.rb
