version: "2"

services:

  #
  # メインコンテナ
  #
  web:
    build:
      context: .

    volumes:
      - .:/app
    ports:
      - "3500:3500"

    environment:
      - PR4_BOT_KEY=${PR4_BOT_KEY}
      - PRIVATE_PEM=${PRIVATE_PEM}

    command: puma -C config/puma.rb
